package views;

import org.h2.mvstore.MVMap;

import model.AnimalData;
import storage.DatabaseInterface;
import storage.FileStoreInterface;
import web.WebRequest;
import web.WebResponse;

public class AnimalEdit extends DynamicWebPage
{

	public AnimalEdit(DatabaseInterface db,FileStoreInterface fs)
	{
		super(db,fs);
	}

	public boolean process(WebRequest toProcess)
	{
		//String id=toProcess.params.get("Animal");
		String id="animal_1519725090990";
		if(toProcess.path.equalsIgnoreCase("AnimalEdit.html"))
		{		
			MVMap<String, AnimalData> animalDetails = db.s.openMap("AnimalData");
			AnimalData Animal = new AnimalData();
			Animal.uniqueid=toProcess.params.get(id);
			System.out.println(Animal.uniqueid);
			Animal=animalDetails.get("animal_1519725090990");
			System.out.println(animalDetails.get(Animal.uniqueid));
			String stringToSendToWebBrowser = "";
			stringToSendToWebBrowser += "<!DOCTYPE HTML>\n";
			stringToSendToWebBrowser += "<html>\n";
			stringToSendToWebBrowser += "\t<head>\n";
			stringToSendToWebBrowser += "\t\t<title>WikiEcosystem</title>\n";
			stringToSendToWebBrowser += "\t\t<meta charset=\"utf-8\" />\t\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"assets/css/main.css\"/>\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"treant/Treant.css\">\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"treant/collapsable.css\">\n";
			stringToSendToWebBrowser += "\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t\t\n";
			stringToSendToWebBrowser += "\t</head>\n";
			stringToSendToWebBrowser += "\t<body>\n";
			stringToSendToWebBrowser += "\t<div id=\"wrapper\">\n";
			stringToSendToWebBrowser += "\t\t<div id=\"main\">\n";
			stringToSendToWebBrowser += "\t\t\t<div class=\"inner\">\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t<!--Info grid-->\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<header class=\"major align-center\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<form name=\"Edit\" action=\"AnimalEdit.html/submit/edit\" method=\"POST\"><h1><input name=\"name\" type=\"text\" value=\""+Animal.animal_name+"\"></h1> \n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<!--Using fixed px here which will be a problem, can't work out how to properly use the css for images-->\n";
			stringToSendToWebBrowser += "                                                    <center><img src=\""+Animal.animal_image+".jpg\" alt=\"Animal Image\" style=\"display:block width:300px;height:300px;\"></center> <br>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t<h3>Animal Description</h3>\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"description\">\""+Animal.animal_description+"\"</textarea>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t<!--Section Two-->\n";
			stringToSendToWebBrowser += "\t\t\t\t<section id=\"3\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t<div class=\"content\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<header class=\"major align-center\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Animal Information</h2> \n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<!-- Table -->\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>Table One</h3>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h4>Scientific Classification</h4>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"table-wrapper\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<thead>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Scientific Name</th>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Description</th>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</thead>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Kingdom</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name =\"kingdom\" type=\"text\" value=\""+Animal.animal_kingdom+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Phylum</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"phylum\" type=\"text\" value=\""+Animal.animal_phylum+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Class</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"class\" type=\"text\" value=\""+Animal.animal_class+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Order</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"order\" type=\"text\" value=\""+Animal.animal_order+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Suborder</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"suborder\" type=\"text\" value=\""+Animal.animal_suborder+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Family</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"family\" type=\"text\" value=\""+Animal.animal_family+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Genus</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name\"genus\" type=\"text\" value=\""+Animal.animal_genus+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Species</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"species\" type\"text\" value=\""+Animal.animal_species+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tfoot>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tfoot>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>Table Two</h3>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h4>General Facts</h4>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"table-wrapper\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<thead>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Statistic</th>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Description</th>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</thead>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Location Primarily Found</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"location\" type=\"text\" value=\""+Animal.animal_location+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Habitat</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"habitat\" type=\"text\" value=\""+Animal.animal_habitat+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Name of Young</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"young\" type=\"text\" value=\""+Animal.animal_name_of_young+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Estimated Population</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"population\" type=\"text\" value=\""+Animal.animal_population+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Prey</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"prey\" type=\"text\" value=\""+Animal.animal_prey+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Predators</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"predators\" type=\"text\" value=\""+Animal.animal_predators+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Average Lifespan</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"lifespan\" type\"text\" value=\""+Animal.animal_average_lifespan+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Average Weight</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"weight\" type=\"text\" value=\""+Animal.animal_weight+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Diet</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"diet\" type=\"text\" value=\""+Animal.animal_diet+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>IUCN Endangered Scale</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input name=\"scale\" type=\"text\" value=\""+Animal.animal_endangered_scale+"\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tfoot>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tfoot>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>Additional Notes</h3>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"Notes\" id=\"Animal_Additional_Notes\" placeholder=\""+Animal.animal_additional_notes+"\" rows=\"6\"></textarea>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<br><input name=\"submit\" type=\"submit\"></form><br>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<ul class=\"actions\"><li><a href=\"newanimal.html\" class=\"button big\">Add new Animal</a></li></ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t</div>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "<!-- Sidebar -->\n";
			stringToSendToWebBrowser += "\t\t<div id=\"sidebar\">\n";
			stringToSendToWebBrowser += "\t\t\t<div class=\"inner\">\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Search -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<section id=\"search\" class=\"alt\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<form name=\"searchForm\" onsubmit=\"return search()\" >\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<input type=\"text\" name=\"query\" id=\"query\" placeholder=\"Search\" />\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</form>\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Menu -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<nav id=\"menu\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<header class=\"major\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<h2>Menu</h2>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"archive.html\">Animals</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"interactive.html\">Interactive</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"login.html\">Login</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"ContactUs.html\">Contact</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t</nav>\t\t\t\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Contact -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<section>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<header class=\"major\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<h2>Login</h2>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<p>Login to the system to contribute and amend animals</p>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<ul class=\"contact\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<form>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li class=\"fa-user\"><input type=\"text\" placeholder=\"Username\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li class=\"fa-lock\"><input type=\"password\" placeholder=\"Password\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><input type=\"submit\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t</form>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Footer -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<footer id=\"footer\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<p class=\"copyright\"> Design: Team 10</p>\n";
			stringToSendToWebBrowser += "\t\t\t\t</footer>\n";
			stringToSendToWebBrowser += "\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t</div>\n";
			stringToSendToWebBrowser += "\t<!-- Scripts -->\n";
			stringToSendToWebBrowser += "\t<script src=\"assets/js/jquery.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"assets/js/skel.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"assets/js/util.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"assets/js/main.js\"></script>\n";
			stringToSendToWebBrowser += "\t</body>\n";
			stringToSendToWebBrowser += "</html>\n";
			toProcess.r = new WebResponse( WebResponse.HTTP_OK, WebResponse.MIME_HTML, stringToSendToWebBrowser );
			return true;
		}
		else if(toProcess.path.equalsIgnoreCase("AnimalEdit.html/submit/edit"))
		{
			MVMap<String, AnimalData> animalDetails = db.s.openMap("AnimalData");
			AnimalData editedAnimal=new AnimalData();
			editedAnimal.uniqueid=id;
			editedAnimal.animal_name=toProcess.params.get("name");
			editedAnimal.animal_description=toProcess.params.get("description");
			editedAnimal.animal_kingdom=toProcess.params.get("kingdom");
			editedAnimal.animal_phylum=toProcess.params.get("phylum");
			editedAnimal.animal_class=toProcess.params.get("class");
			editedAnimal.animal_order=toProcess.params.get("order");
			editedAnimal.animal_suborder=toProcess.params.get("suborder");
			editedAnimal.animal_family=toProcess.params.get("family");
			System.out.println(toProcess.params.get("genus"));
			editedAnimal.animal_genus=toProcess.params.get("genus");
			System.out.println(editedAnimal.animal_genus);
			editedAnimal.animal_species=toProcess.params.get("species");
			editedAnimal.animal_location=toProcess.params.get("location");
			editedAnimal.animal_habitat=toProcess.params.get("habitat");
			editedAnimal.animal_name_of_young=toProcess.params.get("young");
			editedAnimal.animal_population=toProcess.params.get("population");
			editedAnimal.animal_prey=toProcess.params.get("prey");
			editedAnimal.animal_predators=toProcess.params.get("predators");
			editedAnimal.animal_average_lifespan=toProcess.params.get("lifespan");
			editedAnimal.animal_weight=toProcess.params.get("weight");
			editedAnimal.animal_diet=toProcess.params.get("diet");
			editedAnimal.animal_endangered_scale=toProcess.params.get("scale");
			editedAnimal.animal_additional_notes=toProcess.params.get("Notes");
			animalDetails.put(id, editedAnimal);
			db.commit();
			String url="/Animal.html";
			toProcess.r = new WebResponse(WebResponse.HTTP_REDIRECT, WebResponse.MIME_HTML,"<html><body>Redirected: <a href=\""+url+"\">"+url+"</a></body></html>");
			toProcess.r.addHeader("Location", url);
			return true;
		}
		return false;
	}

}
