package views;

import model.AnimalData;
import storage.DatabaseInterface;
import storage.FileStoreInterface;
import web.WebRequest;
import web.WebResponse;

public class Animal extends DynamicWebPage
{

	public Animal(DatabaseInterface db,FileStoreInterface fs)
	{
		super(db,fs);
	}

	public boolean process(WebRequest toProcess)
	{
		if(toProcess.path.equalsIgnoreCase("Animal.html"))
		{
			
			//test case
			AnimalData Animal = new AnimalData();
			Animal.animal_name = "Tiger";
			Animal.animal_description = "This is a test description";
			Animal.animal_kingdom = "Animalia";
			Animal.animal_phylum = "Chordata";
			Animal.animal_class = "Mammalia";
			Animal.animal_order = "Carnivora";
			Animal.animal_suborder = "Feliformia";
			Animal.animal_family = "Felidae";
			Animal.animal_genus = "Panthera";		
			Animal.animal_species = "P. tigris";
			
			Animal.animal_location = "Africa";
			Animal.animal_habitat = "Sahara";
			Animal.animal_prey = "Rodents";
			Animal.animal_name_of_young = "Cubs";
			Animal.animal_predators = "Other lions";
			Animal.animal_average_lifespan = "16 to 18 years";
			Animal.animal_weight = "300 lbs";
			Animal.animal_diet = "Carnivore";
			Animal.animal_endangered_scale = "LC";
			Animal.animal_additional_notes = "This is a test additional note";
			Animal.animal_population = "10000 Tigers";
			
			Animal.animal_image = "Koala";
		
						
			String stringToSendToWebBrowser = "";
			stringToSendToWebBrowser += "<!DOCTYPE HTML>\n";
			stringToSendToWebBrowser += "<html>\n";
			stringToSendToWebBrowser += "\t<head>\n";
			stringToSendToWebBrowser += "\t\t<title>WikiEcosystem</title>\n";
			stringToSendToWebBrowser += "\t\t<meta charset=\"utf-8\" />\t\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"main.css\"/>\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"Treant.css\">\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"collapsable.css\">\n";
			stringToSendToWebBrowser += "\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t\t\n";
			stringToSendToWebBrowser += "\t</head>\n";
			stringToSendToWebBrowser += "\t<body>\n";
			stringToSendToWebBrowser += "\t<div id=\"wrapper\">\n";
			stringToSendToWebBrowser += "\t\t<div id=\"main\">\n";
			stringToSendToWebBrowser += "\t\t\t<div class=\"inner\">\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t<!--Info grid-->\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<header class=\"major align-center\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h1>"+Animal.animal_name+"</h1> \n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<!--Using fixed px here which will be a problem, can't work out how to properly use the css for images-->\n";
			stringToSendToWebBrowser += "                                                    <center><img src=\""+Animal.animal_image+".jpg\" alt=\"Animal Image\" style=\"display:block width:300px;height:300px;\"></center> <br>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t<h3>Animal Description</h3>\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t"+Animal.animal_description+"\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t<!--Section Two-->\n";
			stringToSendToWebBrowser += "\t\t\t\t<section id=\"3\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t<div class=\"content\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<header class=\"major align-center\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>Animal Information</h2> \n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<!-- Table -->\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>Table One</h3>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h4>Scientific Classification</h4>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"table-wrapper\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<thead>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Scientific Name</th>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Description</th>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</thead>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Kingdom</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is part of the "+Animal.animal_kingdom+" Kingdom</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Phylum</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is part of the "+Animal.animal_phylum+"  Phylum</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Class</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is part of the "+Animal.animal_class+" Class</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Order</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is part of the "+Animal.animal_order+" Order</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Suborder</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is part of the "+Animal.animal_suborder+" Suborder</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Family</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is part of the "+Animal.animal_family+" Family</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Genus</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is part of the "+Animal.animal_genus+" Genus</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Species</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is part of the "+Animal.animal_species+" Species</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tfoot>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tfoot>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>Table Two</h3>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h4>General Facts</h4>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"table-wrapper\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<thead>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Statistic</th>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Description</th>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</thead>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Location Primarily Found</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>This animal is primarily found in "+Animal.animal_location+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Habitat</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_habitat+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Name of Young</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_name_of_young+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Estimated Population</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_population+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Prey</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_prey+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Predators</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_predators+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Average Lifespan</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_average_lifespan+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Average Weight</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_weight+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Diet</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_diet+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>IUCN Endangered Scale</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>"+Animal.animal_endangered_scale+"</td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tfoot>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tfoot>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>Additional Notes</h3>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea name=\"Animal_Additional_Notes\" id=\"Animal_Additional_Notes\" placeholder=\""+Animal.animal_additional_notes+"\" rows=\"6\"></textarea>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t\t\t\t\t\t\t\t<br><br>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<ul class=\"actions\"><li><a href=\"newanimal.html\" class=\"button big\">Add new Animal</a></li></ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t\n";
			stringToSendToWebBrowser += "\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t</div>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "<!-- Sidebar -->\n";
			stringToSendToWebBrowser += "\t\t<div id=\"sidebar\">\n";
			stringToSendToWebBrowser += "\t\t\t<div class=\"inner\">\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Search -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<section id=\"search\" class=\"alt\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<form name=\"searchForm\" onsubmit=\"return search()\" >\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<input type=\"text\" name=\"query\" id=\"query\" placeholder=\"Search\" />\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</form>\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Menu -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<nav id=\"menu\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<header class=\"major\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<h2>Menu</h2>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"archive.html\">Animals</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"interactive.html\">Interactive</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"login.html\">Login</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"ContactUs.html\">Contact</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t</nav>\t\t\t\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Contact -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<section>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<header class=\"major\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<h2>Login</h2>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<p>Login to the system to contribute and amend animals</p>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<ul class=\"contact\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<form>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li class=\"fa-user\"><input type=\"text\" placeholder=\"Username\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li class=\"fa-lock\"><input type=\"password\" placeholder=\"Password\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><input type=\"submit\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t</form>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Footer -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<footer id=\"footer\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<p class=\"copyright\"> Design: Team 10</p>\n";
			stringToSendToWebBrowser += "\t\t\t\t</footer>\n";
			stringToSendToWebBrowser += "\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t</div>\n";
			stringToSendToWebBrowser += "\t<!-- Scripts -->\n";
			stringToSendToWebBrowser += "\t<script src=\"jquery.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"skel.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"util.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"main.js\"></script>\n";
			stringToSendToWebBrowser += "\t</body>\n";
			stringToSendToWebBrowser += "</html>\n";
			toProcess.r = new WebResponse( WebResponse.HTTP_OK, WebResponse.MIME_HTML, stringToSendToWebBrowser );
			return true;
		}
		return false;
	}

}