package views;

import storage.DatabaseInterface;
import storage.FileStoreInterface;
import web.WebRequest;
import web.WebResponse;

public class LogIn extends DynamicWebPage
{

	public LogIn(DatabaseInterface db,FileStoreInterface fs)
	{
		super(db,fs);
	}

	public boolean process(WebRequest toProcess)
	{
		if(toProcess.path.equalsIgnoreCase("LogIn.html"))
		{
			String stringToSendToWebBrowser = "";
			stringToSendToWebBrowser += "<!DOCTYPE HTML>\n";
			stringToSendToWebBrowser += "<html>\n";
			stringToSendToWebBrowser += "\t<head>\n";
			stringToSendToWebBrowser += "\t\t<title>WikiEcosystem</title>\n";
			stringToSendToWebBrowser += "\t\t<meta charset=\"utf-8\" />\t\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"main.css\" />\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"Treant.css\">\n";
			stringToSendToWebBrowser += "\t\t<link rel=\"stylesheet\" href=\"collapsable.css\">\n";
			stringToSendToWebBrowser += "\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t\t<script>\n";
			stringToSendToWebBrowser += "\t\t$(document).ready(function(){\n";
			stringToSendToWebBrowser += "\t\t  // Add smooth scrolling to all links\n";
			stringToSendToWebBrowser += "\t\t  $(\"a\").on('click', function(event) {\n";
			stringToSendToWebBrowser += "\t\t\tif (this.hash !== \"\") {\n";
			stringToSendToWebBrowser += "\t\t\t  event.preventDefault();\n";
			stringToSendToWebBrowser += "\t\t\t  var hash = this.hash;\n";
			stringToSendToWebBrowser += "\t\t\t  $('html, body').animate({\n";
			stringToSendToWebBrowser += "\t\t\t\tscrollTop: $(hash).offset().top\n";
			stringToSendToWebBrowser += "\t\t\t  }, 800, function(){\n";
			stringToSendToWebBrowser += "\t\t\t\twindow.location.hash = hash;\n";
			stringToSendToWebBrowser += "\t\t\t  });\n";
			stringToSendToWebBrowser += "\t\t\t}\n";
			stringToSendToWebBrowser += "\t\t  });\n";
			stringToSendToWebBrowser += "\t\t});\n";
			stringToSendToWebBrowser += "\t\t</script>\n";
			stringToSendToWebBrowser += "\t</head>\n";
			stringToSendToWebBrowser += "\t<body>\n";
			stringToSendToWebBrowser += "\t<div id=\"wrapper\">\n";
			stringToSendToWebBrowser += "\t\t<div id=\"main\">\n";
			stringToSendToWebBrowser += "\t\t\t<div class=\"inner\">\t\n";
			stringToSendToWebBrowser += "                <br><br>\n";
			stringToSendToWebBrowser += "                <!-- Header -->\n";
			stringToSendToWebBrowser += "                <div class = \"content align-center\">\t\t\t\t\n";
			stringToSendToWebBrowser += "              <header class=\"major align-center\"> \n";
			stringToSendToWebBrowser += "                <h1>Log In</h1>\n";
			stringToSendToWebBrowser += "              </header>\n";
			stringToSendToWebBrowser += "\t\t\t  <p><b>Please Enter Your Email and Password<p>\n";
			stringToSendToWebBrowser += "\t\t\t  <form method=\"get\" action = onsubmit=\"return checkform(this);\">\n";
			stringToSendToWebBrowser += "\t\t\t  <div class = \"box\">\n";
			stringToSendToWebBrowser += "\t\t\t  <div class = \"tooltip\">\n";
			stringToSendToWebBrowser += "\t\t\t  <input style= \"\" type = \"email\" value =\"\" id=\"email\" placeholder = \"Username\"/>\n";
			stringToSendToWebBrowser += "\t\t\t  <span class=\"tooltiptext\">Type in your Email</span>\n";
			stringToSendToWebBrowser += "\t\t\t  </div>\n";
			stringToSendToWebBrowser += "\t\t\t  <input style = \"width:20.5%; margin-left:39.7%; margin-top:1%;\" type = \"password\" value =\"\" id=\"password\" placeholder = \"Password\"/>\n";
			stringToSendToWebBrowser += "\t\t\t  <!-- START CAPTCHA -->\n";
			stringToSendToWebBrowser += "               <br>\n";
			stringToSendToWebBrowser += "               <div class=\"capbox\">\n";
			stringToSendToWebBrowser += "                <div id=\"CaptchaDiv\"></div>\n";
			stringToSendToWebBrowser += "                 <div class=\"capbox-inner\">\n";
			stringToSendToWebBrowser += "                 Type the above number:<br>\n";
			stringToSendToWebBrowser += "                 <input type=\"hidden\" id=\"txtCaptcha\">\n";
			stringToSendToWebBrowser += "                 <input type=\"text\" name=\"CaptchaInput\" id=\"CaptchaInput\" size=\"15\"><br>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "            </div>\n";
			stringToSendToWebBrowser += "          <br><br>\n";
			stringToSendToWebBrowser += "            <!-- END CAPTCHA -->\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "              <div class = \"12u$\">\n";
			stringToSendToWebBrowser += "              <ul class = \"actions\">\n";
			stringToSendToWebBrowser += "               <li><input type= \"submit\" value = \"Submit\" class = \"special\"/> </li>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "\t\t\t  </form>\n";
			stringToSendToWebBrowser += "\t\t\t  <script type=\"text/javascript\">\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "// Captcha Script\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "function checkform(theform){\n";
			stringToSendToWebBrowser += "var why = \"\";\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "if(theform.CaptchaInput.value == \"\"){\n";
			stringToSendToWebBrowser += "why += \"- Please Enter CAPTCHA Code.\\n\";\n";
			stringToSendToWebBrowser += "}\n";
			stringToSendToWebBrowser += "if(theform.CaptchaInput.value != \"\"){\n";
			stringToSendToWebBrowser += "if(ValidCaptcha(theform.CaptchaInput.value) == false){\n";
			stringToSendToWebBrowser += "why += \"- The CAPTCHA Code Does Not Match.\\n\";\n";
			stringToSendToWebBrowser += "}\n";
			stringToSendToWebBrowser += "}\n";
			stringToSendToWebBrowser += "if(why != \"\"){\n";
			stringToSendToWebBrowser += "alert(why);\n";
			stringToSendToWebBrowser += "return false;\n";
			stringToSendToWebBrowser += "}\n";
			stringToSendToWebBrowser += "}\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "var a = Math.ceil(Math.random() * 9)+ '';\n";
			stringToSendToWebBrowser += "var b = Math.ceil(Math.random() * 9)+ '';\n";
			stringToSendToWebBrowser += "var c = Math.ceil(Math.random() * 9)+ '';\n";
			stringToSendToWebBrowser += "var d = Math.ceil(Math.random() * 9)+ '';\n";
			stringToSendToWebBrowser += "var e = Math.ceil(Math.random() * 9)+ '';\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "var code = a + b + c + d + e;\n";
			stringToSendToWebBrowser += "document.getElementById(\"txtCaptcha\").value = code;\n";
			stringToSendToWebBrowser += "document.getElementById(\"CaptchaDiv\").innerHTML = code;\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "// Validate input against the generated number\n";
			stringToSendToWebBrowser += "function ValidCaptcha(){\n";
			stringToSendToWebBrowser += "var str1 = removeSpaces(document.getElementById('txtCaptcha').value);\n";
			stringToSendToWebBrowser += "var str2 = removeSpaces(document.getElementById('CaptchaInput').value);\n";
			stringToSendToWebBrowser += "if (str1 == str2){\n";
			stringToSendToWebBrowser += "return true;\n";
			stringToSendToWebBrowser += "}else{\n";
			stringToSendToWebBrowser += "return false;\n";
			stringToSendToWebBrowser += "}\n";
			stringToSendToWebBrowser += "}\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "// Remove the spaces from the entered and generated code\n";
			stringToSendToWebBrowser += "function removeSpaces(string){\n";
			stringToSendToWebBrowser += "return string.split(' ').join('');\n";
			stringToSendToWebBrowser += "}\n";
			stringToSendToWebBrowser += "</script>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "           </div>\n";
			stringToSendToWebBrowser += "\t\t   </div>\n";
			stringToSendToWebBrowser += "\t\t</div>\n";
			stringToSendToWebBrowser += "\t</div>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "<!-- Sidebar -->\n";
			stringToSendToWebBrowser += "\t\t<div id=\"sidebar\">\n";
			stringToSendToWebBrowser += "\t\t\t<div class=\"inner\">\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Search -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<section id=\"search\" class=\"alt\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<form name=\"searchForm\" onsubmit=\"return search()\" >\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<input type=\"text\" name=\"query\" id=\"query\" placeholder=\"Search\" />\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</form>\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Menu -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<nav id=\"menu\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<header class=\"major\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<h2>Menu</h2>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"AnimalArchive.html\">Animals</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"interactive.html\">Interactive</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"login.html\">Login</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"signup.html\">Sign Up</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><a href=\"ContactUs.html\">Contact</a></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t</nav>\t\t\t\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Contact -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<section>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<header class=\"major\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<h2>Login</h2>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</header>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<p>Login to the system to contribute and amend animals</p>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<ul class=\"contact\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<form>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li class=\"fa-user\"><input type=\"text\" placeholder=\"Username\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li class=\"fa-lock\"><input type=\"password\" placeholder=\"Password\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t<li><input type=\"submit\"></li>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t\t</form>\n";
			stringToSendToWebBrowser += "\t\t\t\t\t</ul>\n";
			stringToSendToWebBrowser += "\t\t\t\t</section>\n";
			stringToSendToWebBrowser += "\t\t\t\t<!-- Footer -->\n";
			stringToSendToWebBrowser += "\t\t\t\t<footer id=\"footer\">\n";
			stringToSendToWebBrowser += "\t\t\t\t\t<p class=\"copyright\"> Design: Team 10</p>\n";
			stringToSendToWebBrowser += "\t\t\t\t</footer>\n";
			stringToSendToWebBrowser += "\t\t\t</div>\n";
			stringToSendToWebBrowser += "\t\t</div>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "\t<!-- Scripts -->\n";
			stringToSendToWebBrowser += "\t<script src=\"jquery.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"skel.min.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"util.js\"></script>\n";
			stringToSendToWebBrowser += "\t<script src=\"main.js\"></script>\n";
			stringToSendToWebBrowser += "\t</body>\n";
			stringToSendToWebBrowser += "</html>\n";
			toProcess.r = new WebResponse( WebResponse.HTTP_OK, WebResponse.MIME_HTML, stringToSendToWebBrowser );
			return true;
		}
		return false;
	}

}